InformationsSystemOru/Controllers/AdminController.cs
using InformationsSystemOru.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InformationsSystemOru.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        [Authorize]
        public ActionResult Admin()
        {
            if (!User.Identity.IsAdmin())
                return RedirectToAction("Index", "Home");
            return View();
        }
    }
}

InformationsSystemOru/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data_Access_Layer;
using InformationsSystemOru.Models;
using Data_Access_Layer.Repositories;
using System.IO;
using InformationsSystemOru.Extensions;

namespace InformationsSystemOru.Controllers
{
    public class BlogController : Controller
    {
        private AccountRepository accountRep = new AccountRepository();
        private Post_PostTypeRespository postPostType = new Post_PostTypeRespository();
        private PostRepository postrepository = new PostRepository();
        private CommentRepository commentRep = new CommentRepository();
        private UserRepository userRep = new UserRepository();
        private PostTypeRepository _postTypeRepository = new PostTypeRepository();
        private Post_PostTypeRespository _postPostTypeRepository = new Post_PostTypeRespository();

        public BlogModel LoadPosts(List<Post> postList)
        {
            var model = new BlogModel
            {
                AllPosts = new List<PostModel>(),
                loggedInUserId = accountRep.GetIdFromUsername(User.Identity.Name)
            };

            foreach (var post in postList)
            {
                var comments = commentRep.GetPostComments(post.Id);
                var user = userRep.GetUserFromId(post.PostingUserID);

                foreach (var c in comments)
                    c.User = userRep.GetUserFromId((int)c.AuthorId);

                model.AllPosts.Add(new PostModel
                {
                    Category = post.Category,
                    DatePosted = post.Date,
                    Comments = comments,
                    FileUrl = post.FileURL,
                    Filename = post.Filename,
                    PostId = post.Id,
                    Text = post.Text,
                    PostingUserId = post.PostingUserID,
                    PostingUsersName = user.Firstname + " " + user.Lastname,
                    Title = post.Titel,
                    CommentCount = comments.Count(),
                    PostingUsersProfilePicture = user.ProfilePicture == null ? "" : string.Format("data:image/png;base64,{0}", Convert.ToBase64String(user.ProfilePicture))
                });
            }

            model.PostTypes = _postTypeRepository.GetAllPostTypesAfterId3();
            
            foreach (var post in model.AllPosts)
            {
                post.PostType = _postPostTypeRepository.GetPostTypeFromPostId(post.PostId);
            }
            return model;
        }

        [HttpPost]
        public ActionResult PostComment(int postId, string tbComment)
        {
            var loggedInUser = userRep.GetUserFromId(accountRep.GetIdFromUsername(User.Identity.Name));
            var newComment = new Comment
            {
                AuthorId = loggedInUser.Id,
                Date = DateTime.Now,
                Text = tbComment,
                Id = commentRep.GetNewId(),
                PostId = postId
            };

            commentRep.SaveComment(newComment);

            return PartialView("_CommentPartial", new CommentModel
            {
                Authorname = loggedInUser.Firstname + " " + loggedInUser.Lastname,
                Date = newComment.Date,
                Text = newComment.Text,
                CommentId = newComment.Id,
                AuthorId = loggedInUser.Id,
                PostId = postId,
                User = loggedInUser
            });
        }

        [HttpPost]
        public void RemoveComment(int postId, int commentId, int authorId)
        {
            commentRep.RemoveComment(commentId);
        }

        // GET: Blog
        [Authorize]
        public ActionResult InformalBlog()
        {
            var posts = postrepository.GetAllInformalPosts();
            var model = LoadPosts(posts);
            model.CategoryList = postrepository.CategoryListforInformal();

            return View(model);
        }

        public ActionResult GetPostsPartial(List<PostModel> posts)
        {
            var model = new BlogModel
            {
                AllPosts = posts,
                loggedInUserId = accountRep.GetIdFromUsername(User.Identity.Name)
            };
            return PartialView("_PostsPartial", model);
        }

        [Authorize]
        public ActionResult ScienceBlog()
        {
            var posts = postrepository.GetAllSciencePostsKIM();
            var model = LoadPosts(posts);

            return View(model);
        }

        [HttpPost]
        public ActionResult ScienceBlog(BlogModel model)
        {
            var postingUserId = accountRep.GetIdFromUsername(User.Identity.Name);
            string fileName = null;
            string path = null;

            if (model.NewPost.File != null)
            {
                fileName = model.NewPost.File.FileName;
                path = Path.Combine(Path.Combine(Server.MapPath("~/App_Data/Uploads"), fileName));
                model.NewPost.File.SaveAs(path);
            }

            var post = new Post()
            {
                Category = model.NewPost.Category,
                Date = DateTime.Now,
                Titel = model.NewPost.Title,
                Text = model.NewPost.Text,
                PostingUserID = postingUserId,
                FileURL = path,
                Filename = fileName
            };

            postrepository.SavePost(post);
            postPostType.SavePosttype(post.Id, 2);
            return RedirectToAction("Scienceblog");
        }

        [Authorize]
        public ActionResult newsBlog()
        {
            if (!User.Identity.IsAdmin())
                return RedirectToAction("Index", "Home");

            var posts = postrepository.GetAllNewsPosts();
            var model = LoadPosts(posts);

            // TODO: Lägg till PostType för varje post. 

            return View(model);
        }

        [HttpPost]
        public ActionResult NewsBlog(BlogModel model)
        {
            var postingUserId = accountRep.GetIdFromUsername(User.Identity.Name);
            string fileName = null;
            string path = null;

            if (model.NewPost.File != null)
            {
                fileName = model.NewPost.File.FileName;
                path = Path.Combine(Path.Combine(Server.MapPath("~/App_Data/Uploads"), fileName));
                model.NewPost.File.SaveAs(path);
            }

            var post = new Post()
            {
                Category = model.NewPost.Category,
                Date = DateTime.Now,
                Titel = model.NewPost.Title,
                Text = model.NewPost.Text,
                PostingUserID = postingUserId,
                FileURL = path,
                Filename = fileName
            };

            var postType =
                _postTypeRepository.GetPostTypeById(int.Parse(model.NewPost.PostTypeHolder.Substring(0,
                    model.NewPost.PostTypeHolder.LastIndexOf("."))));

            postrepository.SavePost(post);
            postPostType.SavePosttype(post.Id, postType.Id);
            return RedirectToAction("NewsBlog");
        }

        [Authorize]
        public ActionResult EducationBlog()
        {
            //    var loggedInUser = accountRep.GetIdFromUsername(User.Identity.Name);
            var posts = postrepository.GetAllEducationPosts();
            var model = LoadPosts(posts);
            model.CategoryList = postrepository.CategoryListforEducation();

            return View(model);
        }

        [HttpPost]
        public ActionResult EducationBlog(BlogModel model)
        {
            var postingUserId = accountRep.GetIdFromUsername(User.Identity.Name);

            string fileName = null;
            string path = null;

            if (model.NewPost.File != null)
            {
                fileName = model.NewPost.File.FileName;
                path = Path.Combine(Path.Combine(Server.MapPath("~/App_Data/Uploads"), fileName));
                model.NewPost.File.SaveAs(path);
            }
            var post = new Post()
            {
                Category = model.NewPost.Category,
                Date = DateTime.Now,
                Titel = model.NewPost.Title,
                Text = model.NewPost.Text,
                PostingUserID = postingUserId,
                FileURL = path,
                Filename = fileName
            };

            postrepository.SavePost(post);
            postPostType.SavePosttype(post.Id, 3);
            return RedirectToAction("Educationblog");
        }

        [HttpPost]
        public ActionResult DeletePost(int postid, string sida)
        {
            postrepository.DeletePost(postid);
            if (sida == "Education")
                return RedirectToAction("Educationblog");
            else if (sida == "News")
                return RedirectToAction("newsBlog");
            else if (sida == "Profile")
                return RedirectToAction("Profile", "Profile");
            else
                return RedirectToAction("ScienceBlog");

        }

        [HttpPost]
        public ActionResult GetPostsFromCategory(string cat, string department)
        {
            var posts = department == "informal" ? postrepository.GetAllInformalPostsFromCategory(cat) : postrepository.GetAllEducationalPostsFromCategory(cat);
            var model = LoadPosts(posts);
            model.loggedInUserId = accountRep.GetIdFromUsername(User.Identity.Name);

            return PartialView("_PostsPartial", model);
        }


    }
}

InformationsSystemOru/Views/Shared/_CommentPartial.cshtml
@model InformationsSystemOru.Models.CommentModel


<div id="@Model.CommentId">
    <div class="col-md-11">
        
        <div class="media">
            <div class="media-left">
                <a href="@Url.Action("VisitingProfile", "Profile", new { visitedUserID = Model.AuthorId})">
                    @if (Model.User.ProfilePicture == null)
            {
                        <img class="media-object img-rounded" src="~/Content/default.jpg" alt="...">
                    }
                    else
                    {
                        <img class="media-object img-rounded" src="@string.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.User.ProfilePicture))" alt="...">
                    }

                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading"><span class="label label-primary">@Model.Authorname - @Model.Date</span></h4>
                <p>@Model.Text</p>
            </div>
        </div>
        
    </div>

    <div class="col-md-1">
        @using (Ajax.BeginForm("RemoveComment", "Blog", new { postId = Model.PostId, commentId = Model.CommentId, authorId = Model.AuthorId },
    new AjaxOptions { HttpMethod = "POST", OnSuccess = "RemoveComment(" + @Model.CommentId + ")" }))
        {
            <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        }
    </div>
</div>

InformationsSystemOru/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Informatik", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                    <p class="navbar-text">&copy; @DateTime.Now.Year - Informatik, Örebro Universitet</p>
                </div>
            </div>
        </footer>
    </div>
    
</body>
</html>

InformationsSystemOru/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
        });

    </script>
</head>
<body>
    <div class="navbar navbar-default" style="margin: 0px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Informatik", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Science", "ScienceBlog", "Blog")</li>
                            <li>@Html.ActionLink("Education", "EducationBlog", "Blog")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Informal blog", "Informalblog", "Blog")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Calendar", "Calendar", "Meeting")</li>
                    <li>@Html.ActionLink("E-mail", "Contact", "Home")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <button type="button" class="btn btn-success pull-right navbar-btn dropdown-toggle" data-toggle="dropdown" role="button">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> @User.Identity.Name <span class="badge">
                                @{
                                    Html.RenderAction("GetAmountOfMeetings", "Account");
                                }
                            </span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Profile", "Profile", "Profile")</li>
                            <li>
                                <a href="@Url.Action("MyMeetings", "Meeting")">
                                    Meetings
                                    <span class="label label-default label-as-badge">
                                        @{
                                            Html.RenderAction("GetAmountOfMeetings", "Account");
                                        }
                                    </span>
                                </a>
                            </li>
                            <li>@Html.ActionLink("Controlpanel", "Admin", "Admin")</li>
                            <li>@Html.ActionLink("Settings", "ChangeProfilePic", "Profile")</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Home")</li>

                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <br />
        <br />
        <footer style="margin-top: 100px;">
            <div class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                    <p class="navbar-text">&copy; @DateTime.Now.Year - Informatik, Örebro Universitet</p>
                </div>
            </div>
        </footer>
    </div>

</body>
</html>

InformationsSystemOru/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
        });
    </script>
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Informatik", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Science", "ScienceBlog", "Blog")</li>
                            <li>@Html.ActionLink("Education", "EducationBlog", "Blog")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Informal blog", "Informalblog", "Blog")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Calendar", "Calendar", "Meeting")</li>
                    <li>@Html.ActionLink("E-mail", "Contact", "Home")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <button type="button" class="btn btn-success pull-right navbar-btn dropdown-toggle" data-toggle="dropdown" role="button">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> @User.Identity.Name <span class="badge">
                                @{
                                    Html.RenderAction("GetAmountOfMeetings", "Account");
                                }
                            </span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Profile", "Profile", "Profile")</li>
                            <li>
                                <a href="@Url.Action("MyMeetings", "Meeting")">
                                    Meetings
                                    <span class="label label-default label-as-badge">
                                        @{
                                            Html.RenderAction("GetAmountOfMeetings", "Account");
                                        }
                                    </span>
                                </a>
                            </li>
                            <li>@Html.ActionLink("Settings", "ChangeProfilePic", "Profile")</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <br/>
        <br/>
        <footer>
            <div class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                    <p class="navbar-text">&copy; @DateTime.Now.Year - Informatik, Örebro Universitet</p>
                </div>
            </div>

        </footer>
    </div>

</body>
</html>

InformationsSystemOru/Views/Shared/_PostsPartial.cshtml
@model InformationsSystemOru.Models.BlogModel

    @foreach (var post in Model.AllPosts)
    {
        <div class="well well-sm">
            <div class="media">

                <div class="media-left">
                    <a href="@Url.Action("VisitingProfile", "Profile", new { visitedUserID = post.PostingUserId})">
                        @if (post.PostingUsersProfilePicture.IsEmpty())
                {
                            <img class="media-object img-rounded" src="~/Content/default.jpg" alt="...">
                        }
                        else
                        {
                            <img class="media-object img-rounded" src="@post.PostingUsersProfilePicture" alt="...">
                        }

                    </a>
                </div>

                <div class="media-body">

                    <h4 class="media-heading"><strong>@post.Title</strong></h4>
                    <p>@Html.Raw(@post.Text)</p>
                    @if (post.Filename != null)
                    {
                        <a href="@Url.Action("GetFile", "Profile", new{ path = post.FileUrl } )">@post.Filename</a>
                    }
                    <p>Written by <a href="@Url.Action("VisitingProfile", "Profile", new { visitedUserID = post.PostingUserId})">@post.PostingUsersName</a> @post.DatePosted.ToShortDateString() in category @post.Category</p>

                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" href="#collapse@(post.PostId)">Show comments (@post.CommentCount)</a></h4>
                        </div>
                        <div id="collapse@(post.PostId)" class="panel-collapse collapse">
                            <div class="panel-body">
                                @using (Ajax.BeginForm("PostComment", "Blog", new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    InsertionMode = InsertionMode.InsertAfter,
                                    UpdateTargetId = "post" + post.PostId,
                                    OnSuccess = "ClearTextbox()"
                                }))
                                {
                                    <div class="input-group">
                                        @Html.Hidden("postId", post.PostId)
                                        @Html.TextBox("tbComment", "", htmlAttributes: new { @class = "form-control", placeholder = "Write a comment" })
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="submit">Reply</button>
                                        </span>
                                    </div>
                                    <hr />
                                }

                                <div id="post@(post.PostId.ToString())">
                                    @if (post.Comments != null)
                                    {
                                        foreach (var c in post.Comments)
                                        {
                                            <div id="@c.Id">
                                                <div class="col-md-11">

                                                    <div class="media">
                                                        <div class="media-left">
                                                            <a href="@Url.Action("VisitingProfile", "Profile", new { visitedUserID = post.PostingUserId})">
                                                                @if (c.User.ProfilePicture == null)
                                                                {
                                                                    <img class="media-object img-rounded" src="~/Content/default.jpg" alt="...">
                                                                }
                                                                else
                                                                {
                                                                    <img class="media-object img-rounded" src="@string.Format("data:image/png;base64,{0}", Convert.ToBase64String(c.User.ProfilePicture))" alt="...">
                                                                }

                                                            </a>
                                                        </div>
                                                        <div class="media-body">
                                                            <h4 class="media-heading"><span class="label label-primary">@c.User.Firstname @c.User.Lastname - @c.Date</span> </h4>
                                                            <p>@c.Text</p>
                                                        </div>
                                                    </div>

                                                </div>

                                                <div class="col-md-1">
                                                    @if (c.AuthorId == Model.loggedInUserId)
                                                    {
                                                        using (Ajax.BeginForm("RemoveComment", "Blog", new { postId = post.PostId, commentId = c.Id, authorId = c.AuthorId },
                                new AjaxOptions { HttpMethod = "POST", OnSuccess = "RemoveComment(" + @c.Id + ")" }))
                                                        {
                                                            <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                                                        }
                                                    }
                                                </div>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }